UnfinishedMilestone5Code/MinesweeperProjectCLC247/MinesweeperProjectCLC247/Controllers/APIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using GameBoard = MinesweeperProjectCLC247.Models.GameBoardModel;
using Cell = MinesweeperProjectCLC247.Models.CellModel;

namespace MinesweeperProjectCLC247.Controllers
{
    public class APIController : Controller
    {
        // GET: API
        public ActionResult Index()
        {
            //create object model from consumed GameService.svc/GetGrid
            GameAPI.GameServiceClient APIClient = new GameAPI.GameServiceClient();
            int SizeX = APIClient.GetGameBoard().SizeX;
            int SizeY = APIClient.GetGameBoard().SizeY;
            GameBoard board = new GameBoard(SizeX, SizeY, false);

            for (int i = 0; i < (SizeX * SizeY); i++) {
                for (int row = 0; row < SizeY; row++)
                {
                    for (int col = 0; col < SizeX; col++)
                    {
                        var APICell = APIClient.GetGameBoard().Cells[i];
                        Cell cell = new Cell(APICell.Column, APICell.Row, APICell.LiveNeighbors, APICell.IsVisited, APICell.IsLive);

                        board.Cells[row, col] = cell;
                    }
                }
            }
            return View("~/Views/Game/Game", board);
        }
    }
}

UnfinishedMilestone5Code/MinesweeperProjectCLC247/MinesweeperProjectCLC247/Controllers/GameController.cs
using MinesweeperProjectCLC247.Models;
using MinesweeperProjectCLC247.Constants;
using MinesweeperProjectCLC247.Services;
using System;
using System.Diagnostics;
using System.Threading;
using System.Web.Mvc;
using NLog;

namespace MinesweeperProjectCLC247.Controllers {

  

    public class GameController : Controller
    {
        private static Logger logger = LogManager.GetLogger("myAppLoggerRules");

        // GET: Game
        [HttpGet]
        public ActionResult Index() {
            GameBoardModel grid = CreateGrid(25, 25);
            return View("Index", grid);
        }


        public string ElapsedTime()
        {
            TimeSpan ts = Globals.timer.Elapsed;
            Globals.timer.Stop();
            string elapsedtime = String.Format("{0:00}:{1:00}.{2:00}", ts.Minutes, ts.Seconds, ts.Milliseconds / 10);

            return elapsedtime;
        }
      

        // Function to create GLOBAL Grid and fill it with random cells.
        public GameBoardModel CreateGrid(int width, int height)
        {

            Globals.timer.Start();
           
            Globals.Grid = new GameBoardModel(width, height, false);
            CellModel[,] cells = new CellModel[width, height];

            for (int y = 0; y < height; y++)
            {
                for (int x = 0; x < width; x++)
                {
                    cells[x, y] = new CellModel(x, y);
                }
            }

            // Activate the cells
            FillRandomCells(20, width, height, cells, Globals.Grid);

            return Globals.Grid;
        }

        public void FillRandomCells(int percentage, int width, int height, CellModel[,] mineField, GameBoardModel grid)
        {
            Random random = new Random();

            int TotalLiveCount = 0;

            if (percentage > 100 || percentage < 1)
            {
                percentage = 20;
            }
            else
            {
                percentage = (int)((width * height) * (percentage / 100.00));
                TotalLiveCount = percentage;
            }

            while (percentage > 0)
            {
                var cell = mineField[
                    random.Next(0, width),
                    random.Next(0, height)];

                if (cell.IsLive == false)
                {
                    cell.IsLive = true;
                    percentage -= 1;
                }
                else
                {
                    continue;
                }
            }

            grid.Cells = mineField;
            grid.SetLiveCount();
        }


        [HttpPost]
        public PartialViewResult ActivateCell(string x, string y) {
            int Column = int.Parse(x.Trim());
            int Row = int.Parse(y.Trim());
            GameBoardModel grid = Globals.Grid;

            CellModel cell = grid.Cells[Column, Row];

            cell.IsVisited = true;

            if (cell.IsLive) {
                return EndGame();
            } else {
                if (cell.LiveNeighbors == 0) {
                    showNeighbors(grid, cell.Column, cell.Row);
                }
            }
            Globals.numberClicks++;
            return PartialView("Index", grid);
        }
       

        private PartialViewResult EndGame() {
         
            RevealAll();
            return PartialView("Index", Globals.Grid);
        }

        // Function to show the entire grid after losing.
        private void RevealAll()
        {
            Globals.numberClicks++;
           
           
            logger.Info("Number of Clicks = "+Globals.numberClicks.ToString());
            logger.Info("Time Spent in Game = "+ElapsedTime()) ;
            GameBoardModel grid = Globals.Grid;

            grid.HasWon = true;

            for (int i = 0; i < grid.Rows; i++)
            {
                for (int j = 0; j < grid.Cols; j++)
                {
                    grid.Cells[i, j].IsVisited = true;
                }
            }
        }

        // Recursive solution to go through grid and reveal open neighbors.
        private bool showNeighbors(GameBoardModel grid, int x, int y)
        {
            CellModel cell = grid.Cells[x, y];
            cell.IsVisited = true;

            if (cell.LiveNeighbors > 0)
            {
                return false;
            }

            if (cell.Column - 1 >= 0)
            {
                var westLocation = grid.Cells[cell.Column - 1, cell.Row];

                if (!westLocation.IsLive && !westLocation.IsVisited)
                {
                    if (westLocation.LiveNeighbors == 0)
                    {
                        showNeighbors(grid, westLocation.Column, westLocation.Row);
                    }
                    else
                    {
                        westLocation.IsVisited = true;
                    }
                }
            }

            if (cell.Row - 1 >= 0)
            {
                var northLocation = grid.Cells[cell.Column, cell.Row - 1];

                if (!northLocation.IsLive && !northLocation.IsVisited)
                {
                    if (northLocation.LiveNeighbors == 0)
                    {
                        showNeighbors(grid, northLocation.Column, northLocation.Row);
                    }
                    else
                    {
                        northLocation.IsVisited = true;
                    }
                }
            }

            if (cell.Row + 1 < grid.Cols)
            {
                var southLocation = grid.Cells[cell.Column, cell.Row + 1];

                if (!southLocation.IsLive && !southLocation.IsVisited)
                {
                    if (southLocation.LiveNeighbors == 0)
                    {
                        showNeighbors(grid, southLocation.Column, southLocation.Row);
                    }
                    else
                    {
                        southLocation.IsVisited = true;
                    }
                }
            }

            if (cell.Column + 1 < grid.Rows)
            {
                var eastLocation = grid.Cells[cell.Column + 1, cell.Row];

                if (!eastLocation.IsLive && !eastLocation.IsVisited)
                {
                    if (eastLocation.LiveNeighbors == 0)
                    {
                        showNeighbors(grid, eastLocation.Column, eastLocation.Row);
                    }
                    else
                    {
                        eastLocation.IsVisited = true;
                    }
                }
            }
              
            return false;
        }




    }
}

UnfinishedMilestone5Code/MinesweeperProjectCLC247/MinesweeperProjectCLC247/Views/Game/Game.cshtml
@model  MinesweeperProjectCLC247.Models.GameBoardModel

<table id="gameboardTable">
    @for (var y = 0; y < Model.Rows; y++) {
        <tr>
            @for (var x = 0; x < Model.Cols; x++) {
                <td>
                    @if (Model.Cells[x, y].IsVisited) {
                        if (Model.Cells[x, y].IsLive) {
                            <span style="background: black;">
                                <img src="~/Content/mine.png" alt="mine" style="width:32px;height:32px;display:block;" />
                            </span>
                        } else {
                            if (Model.Cells[x, y].LiveNeighbors > 0) {
                                if (Model.Cells[x, y].LiveNeighbors == 1) {
                                    @:<span style="color: blue;">@Model.Cells[x, y].LiveNeighbors</span>
                        }
                                if (Model.Cells[x, y].LiveNeighbors == 2) {
                                    @:<span style="color: green">@Model.Cells[x, y].LiveNeighbors</span>
                        }
                                if (Model.Cells[x, y].LiveNeighbors == 3) {
                                    @:<span style="color: red">@Model.Cells[x, y].LiveNeighbors</span>
                        }
                                if (Model.Cells[x, y].LiveNeighbors == 4) {
                                    @:<span style="color: purple">@Model.Cells[x, y].LiveNeighbors</span>
                        }
                            }
                        }
                    } else {
                        using (Ajax.BeginForm("ActivateCell", "Game", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "gameboardPartial", InsertionMode = InsertionMode.ReplaceWith })) {
                            <input type="hidden" id="x" name="x" value=@Model.Cells[x, y].Column>
                            <input type="hidden" id="y" name="y" value=@Model.Cells[x, y].Row>
                            <button type="submit" id="play" style="background: gray; width:32px;height:32px;display:block;"></button>
                        }
                    }
                </td>
            }
        </tr>
    }
</table>

    <br />
    <form action="/Game" method="post">
        <button type="submit" style="display:none">Restart Game</button>
    </form>

    @using (Html.BeginForm("Index", "API", FormMethod.Post))
    {
        <div>
            <input type="submit" class="btn btn-primary" value="Save Game"/>
        </div>
    }

UnfinishedMilestone5Code/MinesweeperProjectCLC247/MinesweeperProjectCLC247/Views/Game/Index.cshtml
@model  MinesweeperProjectCLC247.Models.GameBoardModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    #gameboardPartial table {
        border: 1px solid;
        border-color: black;
        border-collapse: collapse;
        border: 0;
    }

    #gameboardPartial td {
        border-color: black;
        border: 1px solid;
        background-color: #BCBCBC;
        width: 32px;
        height: 32px;
        text-align: center;
        font-weight: bold;
        vertical-align: middle;
        padding: 0;
    }

    h2 {
        color: black;
    }
</style>

<h2 align="center">
    Minesweeper
</h2>

<div class="container-fluid">
    <div class="row">
        <!-- TITLE -->
    </div>

    <div class="row">
        
        <div class="col-lg-8 col-lg-offset-2">
            <!-- Gameboard -->
            <div id="gameboardPartial">
                @{ Html.RenderPartial("Game", Model); }
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js" type="text/javascript"></script>
}